language: node_js
dist: trusty
node_js: "10"
python: "3.6"
before_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
branches:
  only:
  - master
install:
  - sudo pip3 install -r requirements.txt
  - travis_wait 30 yarn install
cache:
  yarn: true
  directories:
    - node_modules
git:
  lfs_skip_smudge: true
